spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    
resilience4j:
  retry:
    instances:
      jdbcClientRetry:
        max-attempts: 3
        wait-duration: 200ms
        retry-exceptions:
          - java.sql.SQLException
      circuitbreaker:
        instances:
          jdbcClientCB:
            failure-rate-threshold: 50
            wait-duration-in-open-state: 5s
            sliding-window-size: 10
      timelimiter:
        instances:
          jdbcClientTimeout:
            timeout-duration: 3s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
