spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    io.github.resilience4j: DEBUG

resilience4j:
  retry:
    instances:
      jdbc-retry:
        max-attempts: 3
        wait-duration: 300ms
        retry-exceptions:
          - java.sql.SQLException
  circuitbreaker:
    instances:
      jdbc-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        sliding-window-size: 10
  timelimiter:
    instances:
      jdbc-tl:
        timeout-duration: 3s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always